#include "Jeu.h"




void Jeu::lancer()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88--42-1--3c83eccc:14d236af1d7:-8000:0000000000000CC4 begin
{
}
// section -64--88--42-1--3c83eccc:14d236af1d7:-8000:0000000000000CC4 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Jeu::arreter()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88--42-1--3c83eccc:14d236af1d7:-8000:0000000000000CC6 begin
{
}
// section -64--88--42-1--3c83eccc:14d236af1d7:-8000:0000000000000CC6 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Jeu::terminer()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88--42-1--3c83eccc:14d236af1d7:-8000:0000000000000CE1 begin
{
}
// section -64--88--42-1--3c83eccc:14d236af1d7:-8000:0000000000000CE1 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
