#include "Joueur.h"




Joueur::poserTour(Point point, TourAttaque tour)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88--42-1--3c83eccc:14d236af1d7:-8000:0000000000000CD9 begin
{
}
// section -64--88--42-1--3c83eccc:14d236af1d7:-8000:0000000000000CD9 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Joueur::poserTour(Point point, TourRalentissante tour)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88--42-1--3c83eccc:14d236af1d7:-8000:0000000000000CE8 begin
{
}
// section -64--88--42-1--3c83eccc:14d236af1d7:-8000:0000000000000CE8 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
