#include "Monstre.h"




void Monstre::attaquerTour()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88--42-1--3c83eccc:14d236af1d7:-8000:0000000000000CD1 begin
{
}
// section -64--88--42-1--3c83eccc:14d236af1d7:-8000:0000000000000CD1 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Monstre::mourir()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88--42-1--3c83eccc:14d236af1d7:-8000:0000000000000CD3 begin
{
}

void Monstre::setCheminSuivi(Chemin* cheminSuivi) {
    this->cheminSuivi = cheminSuivi;
}

Chemin* Monstre::getCheminSuivi() const {
    return cheminSuivi;
}

void Monstre::setVague(Vague* vague) {
    this->vague = vague;
}

Vague* Monstre::getVague() const {
    return vague;
}
// section -64--88--42-1--3c83eccc:14d236af1d7:-8000:0000000000000CD3 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
