#include "Vague.h"




void Vague::lancer()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88--42-1--3c83eccc:14d236af1d7:-8000:0000000000000CCA begin
{
}

void Vague::setMonstres(vector<Monstre*> monstres) {
    this->monstres = monstres;
}

vector<Monstre*> Vague::getMonstres() const {
    return monstres;
}

void Vague::setNiveau(int niveau) {
    this->niveau = niveau;
}

int Vague::getNiveau() const {
    return niveau;
}
// section -64--88--42-1--3c83eccc:14d236af1d7:-8000:0000000000000CCA end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
